### ISSUE TITLE
Can't install this tool

### ISSUE THREAD

**Issue by lijianyu1985** [kazuhitoyokoi/node-red-contrib-tensorflow#14]
![image](https://user-images.githubusercontent.com/1027001/209905755-702a63a9-c10e-4d19-a9d7-e3036c20931c.png)

![image](https://user-images.githubusercontent.com/1027001/209905924-6f5b497a-6e82-4e64-8ae4-b952226bbb3f.png)

**Comment by kazuhitoyokoi** [comment]
Thank you for the reporting! I mistekenly removed this module from npm repository while testing.
Currently, you can install it on your flow editor.
