### ISSUE TITLE
NodeRed won't work after installing this node on RPi Zero W.

### ISSUE THREAD

**Issue by harish-jachak** [kazuhitoyokoi/node-red-contrib-tensorflow#15]
Hi, Thanks for creating this node.

I tried to install "node-red-contrib-tensorflow" on my NodeRed (v3.0.2) instance on Raspberry Pi Zero W using Pallate Manager. It was taking a long time, so I left the installation process for some time. When I got back the NodeRed had crashed and was not reachable on URL. 

I could reach Pi by SSH (only NodeRed was not working) and so tried to restart Node Red. "node-red-restart", "node-red-start" and "node-red-start --safe" all commands gave me following error.

harish@raspberrypi:~ $ node-red-start --safe

Start Node-RED

Once Node-RED has started, point a browser at http://192.168.31.229:1880
On Pi Node-RED works better with the Firefox or Chrome browser

Use   node-red-stop                          to stop Node-RED
Use   node-red-start                         to start Node-RED again
Use   node-red-log                           to view the recent log output
Use   sudo systemctl enable nodered.service  to autostart Node-RED at every boot
Use   sudo systemctl disable nodered.service to disable autostart on boot

To find more nodes and example flows - go to http://flows.nodered.org

Starting as a systemd service.
Platform node has already been set. Overwriting the platform with node.
nodered.service: Main process exited, code=killed, status=4/ILL
nodered.service: Failed with result 'signal'.
nodered.service: Consumed 1min 1.733s CPU time.
nodered.service: Scheduled restart job, restart counter is at 89.
Stopped Node-RED graphical event wiring tool.
nodered.service: Consumed 1min 1.733s CPU time.
Started Node-RED graphical event wiring tool.
4 Jan 17:07:52 - [info]
Welcome to Node-RED
===================
4 Jan 17:07:52 - [info] Node-RED version: v3.0.2
4 Jan 17:07:52 - [info] Node.js  version: v16.19.0
4 Jan 17:07:52 - [info] Linux 5.15.76+ arm LE
4 Jan 17:08:00 - [info] Loading palette nodes
Platform node has already been set. Overwriting the platform with node.
nodered.service: Main process exited, code=killed, status=4/ILL
nodered.service: Failed with result 'signal'.
nodered.service: Consumed 1min 1.467s CPU time.
nodered.service: Scheduled restart job, restart counter is at 90.
Stopped Node-RED graphical event wiring tool.
nodered.service: Consumed 1min 1.467s CPU time.
Started Node-RED graphical event wiring tool.
4 Jan 17:09:14 - [info]
Welcome to Node-RED
===================
4 Jan 17:09:14 - [info] Node-RED version: v3.0.2
4 Jan 17:09:14 - [info] Node.js  version: v16.19.0
4 Jan 17:09:14 - [info] Linux 5.15.76+ arm LE
4 Jan 17:09:23 - [info] Loading palette nodes
Platform node has already been set. Overwriting the platform with node.
nodered.service: Main process exited, code=killed, status=4/ILL
nodered.service: Failed with result 'signal'.
nodered.service: Consumed 1min 1.895s CPU time.
^C

Also, I could see files related to this node in .node-red directory. Finally decided to uninstall using NPM command. As soon as node got uninstalled NodeRed started working again. (without even a restart).

**Comment by kazuhitoyokoi** [comment]
Thank you for raising the issue. I tested this node on Raspberry Pi 4 only. Because Raspberry Pi Zero W has little memory and the process takes a long time, please use Raspberry Pi 4.
