### ISSUE TITLE
Unexpected token * (line:4)

### ISSUE THREAD

**Issue by ozmule** [kazuhitoyokoi/node-red-contrib-tensorflow#2]
Node-RED version: v1.1.0
Node.js  version: v10.21.0
Linux 4.15.0-106-generic x64 LE (running on Docker)

Installed via Palette

6 Jul 17:24:53 - [info] Installing module: node-red-contrib-tensorflow, version: 0.1.8,
6 Jul 17:25:30 - [info] Installed module: node-red-contrib-tensorflow,
6 Jul 17:25:30 - [info] Added node types:,
6 Jul 17:25:30 - [info]  - node-red-contrib-tensorflow:cocossd : SyntaxError: Unexpected token * (line:4),
6 Jul 17:25:30 - [info]  - node-red-contrib-tensorflow:handpose : SyntaxError: Unexpected token * (line:4),
6 Jul 17:25:30 - [info]  - node-red-contrib-tensorflow:mobilenet : SyntaxError: Unexpected token * (line:4),
6 Jul 17:25:30 - [info]  - node-red-contrib-tensorflow:posenet : SyntaxError: Unexpected token * (line:4),

![image](https://user-images.githubusercontent.com/63888591/86568912-f68ff400-bfb0-11ea-9238-6afcb5e1a743.png)

**Comment by kazuhitoyokoi** [comment]
@ozmule Thank you for this report. I encountered the same error when I'm using Node-RED on IBM Cloud today.

**Comment by ozmule** [comment]
@kazuhitoyokoi great. Is there anything else I can assist and provide from my end?

**Comment by kazuhitoyokoi** [comment]
@ozmule The problem seems to occur from the latest coco-ssd module. Therefore, I used the old version, v2.0.3 and I published v0.1.9 on npmjs and flow library. Could you check the node?

**Comment by ozmule** [comment]
@kazuhitoyokoi that fixed the install issue. I'll continue testing and let you know if anything else happens. Thank you for being so responsive and great work!

**Comment by ozmule** [comment]
When trying to use cocossd node you get the following error

`TypeError: response.arrayBuffer is not a function`

When you deploy after adding the node to the flow you get the following

![image](https://user-images.githubusercontent.com/63888591/86664951-89bd3e00-c032-11ea-89fe-e65559418837.png)

`7 Jul 09:19:38 - [error] [cocossd:4652ace5.1a4934] TypeError: response.arrayBuffer is not a function
7 Jul 09:19:38 - [error] [cocossd:4652ace5.1a4934] TypeError: response.arrayBuffer is not a function
(node:16) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'detect' of undefined
    at /data/node_modules/node-red-contrib-tensorflow/tensorflow.js:49:34
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)`

HTH

**Comment by kazuhitoyokoi** [comment]
I close this issue and create the new issue.
