### ISSUE TITLE
Installation of tensorflow keep loading 

### ISSUE THREAD

**Issue by llhoang** [kazuhitoyokoi/node-red-contrib-tensorflow#7]
Dear kazuhitoyokoi

May I know what is the reason behind that keeps the installation of node-red-contrib-tensorflow loading even by using cmd or install via node-red interface?

I try to let my computer install it by using different way but it keeps loading all the time ? Can you please help me with it ? 

![image](https://user-images.githubusercontent.com/91138416/134186105-a1b0123f-c5e3-46ec-a295-b08f2b2241e9.png)

![image](https://user-images.githubusercontent.com/91138416/134186424-08996d4e-0416-4500-a659-a22b91e38858.png)

Really appreciate

Kind Regards

**Comment by kazuhitoyokoi** [comment]
Thank you for using the TensorFlow node. I'm not sure why the process has no progress. I recommend the Ubuntu environment for this node. Is it possible to use WSL2 on your Windows environment?
