### ISSUE TITLE
REQUEST - Get price from ticket

### ISSUE THREAD

**Issue by Yusseiin** [kazuhitoyokoi/node-red-contrib-tensorflow#9]
Hi, 
may i ask if will be possibile with the tensorflow to get prices from a photo of a ticket ?
If yes, it need a new version of the app or it can be possible to import another " pre-trained TensorFlow" ?
Sorry for bad eng

**Comment by kazuhitoyokoi** [comment]
Thank you for your using my nodes! This TensorFlow.js nodes don't support OCR and import pre-trained models. I think Google's OCR API will be your solution.
